server:
  port: 9090
  servlet:
    context-path: /demo

spring:
  dubbo:
    application:
      name: spring-boot-demo-dubbo-provider2
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881

logging:
  level:
    root: info
